合并Dev
MuRainBot/MuRainBot2 pull request #12
Opened 2024-03-24 14:35 UTC by xiaosuyyds

合并Dev最近的几个更改

2024-03-26 14:53 UTC, BigCookie233 requested changes

2024-03-26 14:53 UTC, BigCookie233 commented on README.md
> +|   ├─ ConfigMainanager.py MRB2的Lib库之一，用于管理配置文件
打字的时候能不能认真点

2024-03-28 14:24 UTC, HarcicYang approved these changes
打字能不能认真点

2024-03-28 14:24 UTC, HarcicYang approved these changes

2024-03-28 14:25 UTC, xiaosuyyds commented
> 打字能不能认真点

全是输入法的锅（
总之知道了，以后可能大概应该会改吧

2024-03-28 14:33 UTC, BigCookie233 approved these changes

2024-03-28 14:33 UTC, merged